### ISSUE TITLE
Add endpoint to query results

### ISSUE THREAD

**Issue by Bugadinho** [vinegarhq/merlin#3]
It would be immensely useful for other projects to be able to query for results without having to resort to ask for the CSV file, this is the only blocker to integrating it into Cork.

**Comment by sewnie** [comment]
Merlin is currently still in testing and not ready for deployment, however if made public, the CSV will be made public, may or may not be fully public via a file endpoint.

**Comment by Bugadinho** [comment]
Well that makes sense, I'll look into integrating it soon then. Should i close this issue?

**Comment by sewnie** [comment]
No, as the CSV is still not public.

**Comment by lunarlattice0** [comment]
I think I may set up a cronjob to upload the CSV to a github gist.

**Comment by lunarlattice0** [comment]
@Bugadinho Okay, I've made the CSV open for download at https://merlin.vinegarhq.org. Please note that it is set to download as a file and will NOT provide a filename.
